package k3.daybook.data.model;

import java.util.Date;

import io.realm.RealmObject;
import k3.daybook.util.DBUtil;

/**
 * @author Kyson LEE
 */
public class Record extends RealmObject {

    // the primary key of the table record
    /**
     * the unique id for an record
     */
    private long id;

    // the non-null content for the table
    /**
     * the date when this piece of record is created
     * generated by the system
     */
    private Date date;
    /**
     * the amount of the certain dealing
     */
    private float amount;
    /**
     * where you spend you money
     * 1: Clothing
     * 2: Food
     * 3: Residence
     * 4: Transport
     * 5: Leisure
     * 6: Else
     * 7: Salary
     * positive if it is paid out, otherwise, negative
     */
    private Usage usage;
    /**
     * the method you pay for the deal
     * can be modified by user
     */
    private Payment payment;

    // optional, used as a supplement
    /**
     * scenarios, etc.
     */

    public Record() {
        id = DBUtil.getLatestId(Record.class) + 1;
        date = new Date(System.currentTimeMillis());
        amount = 0;
        usage = null;
        payment = null;
    }

    public void updateRecord(Record record) {
        amount = record.getAmount();
        usage = record.getUsage();
        payment = record.getPayment();
    }

    public float getAmount() {
        return amount;
    }

    public void setAmount(float amount) {
        this.amount = amount;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Payment getPayment() {
        return payment;
    }

    public void setPayment(Payment payment) {
        this.payment = payment;
    }

    public Usage getUsage() {
        return usage;
    }

    public void setUsage(Usage usage) {
        this.usage = usage;
    }
}
