package k3.daybook.record.model;

import java.util.Date;

import io.realm.RealmObject;
import k3.daybook.util.RealmUtil;

/**
 * @author Kyson LEE
 */
public class Record extends RealmObject {

    // the primary key of the table record
    /**
     * the unique id for an record
     */
    private long id;

    // the non-null content for the table
    /**
     * the date when this piece of record is created
     * generated by the system
     */
    private Date date;
    /**
     * the amount of the certain dealing
     */
    private float amount;
    /**
     * where you spend you money
     * 1: Clothing
     * 2: Food
     * 3: Residence
     * 4: Transport
     * 5: Leisure
     * 6: Else
     * 7: Salary
     * positive if it is paid out, otherwise, negative
     */
    private int consume;
    /**
     * the method you pay for the deal
     * can be modified by user
     */
    private long accountId;

    // optional, used as a supplement
    /**
     * scenarios, etc.
     */
    private String comment;

    public static final String ID = "id";
    public static final String DATE = "date";
    public static final String AMOUNT = "amount";
    public static final String CONSUME = "consume";
    public static final String ACCOUNTID = "accountId";
    public static final String COMMENT = "comment";

    public static final int CONSUMING_UNDEFINED = 0;
    public static final int CONSUMING_CLOTHING = 1;
    public static final int CONSUMING_FOOD = 2;
    public static final int CONSUMING_LODGEMENT = 3;
    public static final int CONSUMING_TRANSPORT = 4;
    public static final int CONSUMING_LEISURE = 5;
    public static final int CONSUMING_ELSE = 6;
    public static final int CONSUMING_SALARY = 7;

    public void initRecord() {
        id = RealmUtil.getLatestRecordId();
        date = new Date(System.currentTimeMillis());
        amount = 0;
        consume = CONSUMING_UNDEFINED;
        accountId = 0;
        comment = "";
    }

    public void updateRecord(Record record) {
        amount = record.getAmount();
        consume = record.getConsume();
        accountId = record.getAccountId();
        comment = record.getComment();
    }

    public float getAmount() {
        return amount;
    }

    public void setAmount(float amount) {
        this.amount = amount;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public int getConsume() {
        return consume;
    }

    public void setConsume(int consume) {
        this.consume = consume;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getAccountId() {
        return accountId;
    }

    public void setAccountId(long accountId) {
        this.accountId = accountId;
    }

    @Override
    public String toString() {
        return "Record{" + "accountId=" + accountId + ", id=" + id + ", date=" + date + ", amount="
                + amount + ", consume=" + consume + ", comment='" + comment + '\'' + '}';
    }
}
